name = "wai-worker"
main = "src/worker/index.ts"
compatibility_date = "2022-05-03"
node_compat = true

[dev]
ip = "localhost"

[[r2_buckets]]
# binding 的值 需要跟 [vars] / R2_STORAGE_BINGDING_KEY 一致
binding = 'STORAGE'
# 在 https://dash.cloudflare.com/ > R2 > Overview : Create bucket
bucket_name = 'wai-r2-prod'
preview_bucket_name="wai-r2-preview"

[[kv_namespaces]]
# binding 的值 需要跟 [vars] / KV_NAMESPACE_BINDING_KEY 一致
# 在 https://dash.cloudflare.com/ > Workers > KV : Create a namespace
binding = "DATABASE"
id = ""
preview_id = ""

[vars]
KV_NAMESPACE_BINDING_KEY="DATABASE"
R2_STORAGE_BINGDING_KEY="STORAGE"

IS_PROD = true
USER_ID_START = "10000"
WAI_WORKER_API_TOKEN = ""
Access_Control_Allow_Origin = "*"

# media 采用 AES gcm 加密存储 需要用到 32位 key，16位 iv 和 aad，请使用 {worker_url}/utils/random 生成
# "404b337e424aa1e81ab7ff0212d624316678c8c71f85f2587cced2979691e4e6".length = 64
# Buffer.from("404b337e424aa1e81ab7ff0212d624316678c8c71f85f2587cced2979691e4e6","hex").length = 32
MEDIA_ENCRYPT_KEY_32_BITS="404b337e424aa1e81ab7ff0212d624316678c8c71f85f2587cced2979691e4e6"
MEDIA_ENCRYPT_IV_16_BITS="455665f90fe2c058413926312409a415"
MEDIA_ENCRYPT_AAD_16_BITS="90ad87efbeb9b5fdd4f5f106690596ef"
